Traceback (most recent call last):
  File "/home/marco/.cache/pypoetry/virtualenvs/torch-mist-77TFSLfY-py3.9/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/marco/.cache/pypoetry/virtualenvs/torch-mist-77TFSLfY-py3.9/lib/python3.9/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/marco/.cache/pypoetry/virtualenvs/torch-mist-77TFSLfY-py3.9/lib/python3.9/site-packages/jupyter_core/utils/__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
  File "/home/marco/anaconda3/envs/torch-mist/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/home/marco/.cache/pypoetry/virtualenvs/torch-mist-77TFSLfY-py3.9/lib/python3.9/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/home/marco/.cache/pypoetry/virtualenvs/torch-mist-77TFSLfY-py3.9/lib/python3.9/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/marco/.cache/pypoetry/virtualenvs/torch-mist-77TFSLfY-py3.9/lib/python3.9/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from torch_mist.utils.data import SampleDataLoader

trainloader = SampleDataLoader(
    p_xy,
    batch_size=64,
    max_samples=100000 # Number of samples per epoch
)

testloader = SampleDataLoader(
    p_xy,
    batch_size=64,
    max_samples=10000,
)


# This dataloader simply returns pairs of samples from p(x,y)
# with shape [batch_size, X_DIM] [batch_size, Y_DIM]
for x, y in trainloader:
    break

print(x.shape, y.shape)
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mImportError[0m                               Traceback (most recent call last)
Cell [0;32mIn[5], line 1[0m
[0;32m----> 1[0m [38;5;28;01mfrom[39;00m [38;5;21;01mtorch_mist[39;00m[38;5;21;01m.[39;00m[38;5;21;01mutils[39;00m[38;5;21;01m.[39;00m[38;5;21;01mdata[39;00m [38;5;28;01mimport[39;00m SampleDataLoader
[1;32m      3[0m trainloader [38;5;241m=[39m SampleDataLoader(
[1;32m      4[0m     p_xy,
[1;32m      5[0m     batch_size[38;5;241m=[39m[38;5;241m64[39m,
[1;32m      6[0m     max_samples[38;5;241m=[39m[38;5;241m100000[39m [38;5;66;03m# Number of samples per epoch[39;00m
[1;32m      7[0m )
[1;32m      9[0m testloader [38;5;241m=[39m SampleDataLoader(
[1;32m     10[0m     p_xy,
[1;32m     11[0m     batch_size[38;5;241m=[39m[38;5;241m64[39m,
[1;32m     12[0m     max_samples[38;5;241m=[39m[38;5;241m10000[39m,
[1;32m     13[0m )

[0;31mImportError[0m: cannot import name 'SampleDataLoader' from 'torch_mist.utils.data' (/home/marco/Documents/PhD/torch_mist/src/torch_mist/utils/data/__init__.py)

