Traceback (most recent call last):
  File "/home/marco/.cache/pypoetry/virtualenvs/torch-mist-77TFSLfY-py3.9/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/marco/.cache/pypoetry/virtualenvs/torch-mist-77TFSLfY-py3.9/lib/python3.9/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/marco/.cache/pypoetry/virtualenvs/torch-mist-77TFSLfY-py3.9/lib/python3.9/site-packages/jupyter_core/utils/__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
  File "/home/marco/anaconda3/envs/torch-mist/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/home/marco/.cache/pypoetry/virtualenvs/torch-mist-77TFSLfY-py3.9/lib/python3.9/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/home/marco/.cache/pypoetry/virtualenvs/torch-mist-77TFSLfY-py3.9/lib/python3.9/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/marco/.cache/pypoetry/virtualenvs/torch-mist-77TFSLfY-py3.9/lib/python3.9/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import torch_mist

print(torch_mist.__version__)
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mOSError[0m                                   Traceback (most recent call last)
File [0;32m~/.cache/pypoetry/virtualenvs/torch-mist-77TFSLfY-py3.9/lib/python3.9/site-packages/torch/__init__.py:168[0m, in [0;36m_load_global_deps[0;34m()[0m
[1;32m    167[0m [38;5;28;01mtry[39;00m:
[0;32m--> 168[0m     [43mctypes[49m[38;5;241;43m.[39;49m[43mCDLL[49m[43m([49m[43mlib_path[49m[43m,[49m[43m [49m[43mmode[49m[38;5;241;43m=[39;49m[43mctypes[49m[38;5;241;43m.[39;49m[43mRTLD_GLOBAL[49m[43m)[49m
[1;32m    169[0m [38;5;28;01mexcept[39;00m [38;5;167;01mOSError[39;00m [38;5;28;01mas[39;00m err:
[1;32m    170[0m     [38;5;66;03m# Can only happen for wheel with cuda libs as PYPI deps[39;00m
[1;32m    171[0m     [38;5;66;03m# As PyTorch is not purelib, but nvidia-*-cu11 is[39;00m

File [0;32m~/anaconda3/envs/torch-mist/lib/python3.9/ctypes/__init__.py:382[0m, in [0;36mCDLL.__init__[0;34m(self, name, mode, handle, use_errno, use_last_error, winmode)[0m
[1;32m    381[0m [38;5;28;01mif[39;00m handle [38;5;129;01mis[39;00m [38;5;28;01mNone[39;00m:
[0;32m--> 382[0m     [38;5;28mself[39m[38;5;241m.[39m_handle [38;5;241m=[39m [43m_dlopen[49m[43m([49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_name[49m[43m,[49m[43m [49m[43mmode[49m[43m)[49m
[1;32m    383[0m [38;5;28;01melse[39;00m:

[0;31mOSError[0m: libcurand.so.10: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

[0;31mValueError[0m                                Traceback (most recent call last)
Cell [0;32mIn[1], line 1[0m
[0;32m----> 1[0m [38;5;28;01mimport[39;00m [38;5;21;01mtorch_mist[39;00m
[1;32m      3[0m [38;5;28mprint[39m(torch_mist[38;5;241m.[39m__version__)

File [0;32m~/Documents/PhD/torch_mist/src/torch_mist/__init__.py:4[0m
[1;32m      2[0m [38;5;28;01mfrom[39;00m [38;5;21;01mimportlib[39;00m[38;5;21;01m.[39;00m[38;5;21;01mmetadata[39;00m [38;5;28;01mimport[39;00m version
[1;32m      3[0m __version__ [38;5;241m=[39m version([38;5;124m"[39m[38;5;124mtorch_mist[39m[38;5;124m"[39m)
[0;32m----> 4[0m [38;5;28;01mfrom[39;00m [38;5;21;01mtorch_mist[39;00m[38;5;21;01m.[39;00m[38;5;21;01mutils[39;00m[38;5;21;01m.[39;00m[38;5;21;01mestimation[39;00m [38;5;28;01mimport[39;00m estimate_mi

File [0;32m~/Documents/PhD/torch_mist/src/torch_mist/utils/__init__.py:1[0m
[0;32m----> 1[0m [38;5;28;01mfrom[39;00m [38;5;21;01m.[39;00m[38;5;21;01mestimation[39;00m [38;5;28;01mimport[39;00m evaluate_mi, estimate_mi

File [0;32m~/Documents/PhD/torch_mist/src/torch_mist/utils/estimation.py:4[0m
[1;32m      1[0m [38;5;28;01mfrom[39;00m [38;5;21;01mtyping[39;00m [38;5;28;01mimport[39;00m Tuple, Optional, Any, Union, Type, Dict
[1;32m      3[0m [38;5;28;01mimport[39;00m [38;5;21;01mpandas[39;00m [38;5;28;01mas[39;00m [38;5;21;01mpd[39;00m
[0;32m----> 4[0m [38;5;28;01mimport[39;00m [38;5;21;01mtorch[39;00m
[1;32m      5[0m [38;5;28;01mimport[39;00m [38;5;21;01mnumpy[39;00m [38;5;28;01mas[39;00m [38;5;21;01mnp[39;00m
[1;32m      6[0m [38;5;28;01mfrom[39;00m [38;5;21;01mtorch[39;00m[38;5;21;01m.[39;00m[38;5;21;01moptim[39;00m [38;5;28;01mimport[39;00m Optimizer, Adam

File [0;32m~/.cache/pypoetry/virtualenvs/torch-mist-77TFSLfY-py3.9/lib/python3.9/site-packages/torch/__init__.py:228[0m
[1;32m    217[0m [38;5;28;01melse[39;00m:
[1;32m    218[0m     [38;5;66;03m# Easy way.  You want this most of the time, because it will prevent[39;00m
[1;32m    219[0m     [38;5;66;03m# C++ symbols from libtorch clobbering C++ symbols from other[39;00m
[0;32m   (...)[0m
[1;32m    225[0m     [38;5;66;03m#[39;00m
[1;32m    226[0m     [38;5;66;03m# See Note [Global dependencies][39;00m
[1;32m    227[0m     [38;5;28;01mif[39;00m USE_GLOBAL_DEPS:
[0;32m--> 228[0m         [43m_load_global_deps[49m[43m([49m[43m)[49m
[1;32m    229[0m     [38;5;28;01mfrom[39;00m [38;5;21;01mtorch[39;00m[38;5;21;01m.[39;00m[38;5;21;01m_C[39;00m [38;5;28;01mimport[39;00m [38;5;241m*[39m  [38;5;66;03m# noqa: F403[39;00m
[1;32m    231[0m [38;5;66;03m# Appease the type checker; ordinarily this binding is inserted by the[39;00m
[1;32m    232[0m [38;5;66;03m# torch._C module initialization code in C[39;00m

File [0;32m~/.cache/pypoetry/virtualenvs/torch-mist-77TFSLfY-py3.9/lib/python3.9/site-packages/torch/__init__.py:189[0m, in [0;36m_load_global_deps[0;34m()[0m
[1;32m    187[0m     [38;5;28;01mraise[39;00m err
[1;32m    188[0m [38;5;28;01mfor[39;00m lib_folder, lib_name [38;5;129;01min[39;00m cuda_libs[38;5;241m.[39mitems():
[0;32m--> 189[0m     [43m_preload_cuda_deps[49m[43m([49m[43mlib_folder[49m[43m,[49m[43m [49m[43mlib_name[49m[43m)[49m
[1;32m    190[0m ctypes[38;5;241m.[39mCDLL(lib_path, mode[38;5;241m=[39mctypes[38;5;241m.[39mRTLD_GLOBAL)

File [0;32m~/.cache/pypoetry/virtualenvs/torch-mist-77TFSLfY-py3.9/lib/python3.9/site-packages/torch/__init__.py:154[0m, in [0;36m_preload_cuda_deps[0;34m(lib_folder, lib_name)[0m
[1;32m    152[0m         [38;5;28;01mbreak[39;00m
[1;32m    153[0m [38;5;28;01mif[39;00m [38;5;129;01mnot[39;00m lib_path:
[0;32m--> 154[0m     [38;5;28;01mraise[39;00m [38;5;167;01mValueError[39;00m([38;5;124mf[39m[38;5;124m"[39m[38;5;132;01m{[39;00mlib_name[38;5;132;01m}[39;00m[38;5;124m not found in the system path [39m[38;5;132;01m{[39;00msys[38;5;241m.[39mpath[38;5;132;01m}[39;00m[38;5;124m"[39m)
[1;32m    155[0m ctypes[38;5;241m.[39mCDLL(lib_path)

[0;31mValueError[0m: libcublas.so.*[0-9] not found in the system path ['/home/marco/Documents/PhD/torch_mist/docs', '/home/marco/anaconda3/envs/torch-mist/lib/python39.zip', '/home/marco/anaconda3/envs/torch-mist/lib/python3.9', '/home/marco/anaconda3/envs/torch-mist/lib/python3.9/lib-dynload', '', '/home/marco/.cache/pypoetry/virtualenvs/torch-mist-77TFSLfY-py3.9/lib/python3.9/site-packages', '/home/marco/Documents/PhD/torch_mist/src']

